---
- hosts: jenkins-slave
  become: true
  tasks:
      - name: install docker
        apt:
          name: docker.io
          state: present


      - name: start docker 
        service:
          name: docker
          state: started

      - name: start docker after reboot
        service:
          name: docker
          enabled: yes
      

      - name: give 777 permissions on /var/run/docker.sock
        file:
          path: /var/run/docker.sock
          state: file
          mode: 0777
