---
- hosts: jenkins-master 
  become: true #root
  tasks:
  - name: add jenkins key
     apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present

  - name: add jenkins rep
     apt_repository: 
      rep: 'deb https://pkg.jenkins.io/debian-stable binary/'
      state: present

  - name: install java
    apt:
      name: openjdk-11-jre
      state: present

  - name: install jenkins
    apt:
      name: jenkins
      state: present

  - name: start jenkins
    service:
      name: jenkins
      state: started


  - name: start jenkins after reboot
    service:
      name: jenkins
      enabled: yes